version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_bs
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_bs
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web:latest
    container_name: bs_backend_app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"

volumes:
  data: {}
